'use strict';
// ═══════════════════════════════════════════════════════════════════════════
// typed-schemas.js — Esquemas de las tablas tipadas por entidad (Fase 3B)
//
// GENERADO desde los datos REALES del PG de producción (22-jul-2026):
//   SELECT collection, k, jsonb_typeof(data->k), count(*)
//   FROM collection_rows, LATERAL jsonb_object_keys(data) k GROUP BY 1,2,3
// Reglas (conservadoras, roundtrip sin pérdida — ver storage-pg.js):
//   string→text · boolean→boolean · number→float8 (exacto <2^53) ·
//   object/array/tipo MIXTO entre filas→jsonb · claves nuevas o con drift
//   de tipo → columna _extra JSONB (nunca se pierde nada).
// Cada tabla t_<coleccion> lleva además: _key TEXT PK (clave de fila del
// storage), _ord DOUBLE PRECISION (orden del array) y _extra JSONB.
// Para regenerar: scratchpad/gen-schema.mjs de la sesión 22-jul (o repetir la
// query de arriba y aplicar las mismas reglas).
// ═══════════════════════════════════════════════════════════════════════════

const TYPED_SCHEMAS = {
  'averias': {
    "barcode": 'text',
    "comentario": 'text',
    "createdAt": 'text',
    "id": 'text',
    "image": 'text',
    "location": 'text',
    "name": 'text',
    "qty": 'float8',
    "ref": 'text',
    "status": 'text',
    "statusHistory": 'jsonb',
    "updatedAt": 'text',
    "wwpItemId": 'text',
    "wwpOdooRef": 'text',
    "wwpTaskId": 'text',
    "wwpTaskTitle": 'text',
    "wwpTaskType": 'text',
  },
  'despachos-obsoleto': {
    "creadoPor": 'jsonb',
    "createdAt": 'text',
    "estado": 'text',
    "folio": 'text',
    "id": 'text',
    "importedTransfers": 'jsonb',
    "lineas": 'jsonb',
    "migrationKey": 'text',
    "nota": 'text',
    "receptor": 'jsonb',
    "seq": 'float8',
    "transferLink": 'text',
    "transportista": 'text',
    "updatedAt": 'text',
    "vehiculo": 'text',
    "version": 'float8',
  },
  'emp-materiales': {
    "descripcion": 'text',
    "id": 'text',
    "nombre": 'text',
  },
  'emp-reglas': {
    "categ_id": 'float8',
    "categ_nombre": 'text',
    "id": 'text',
    "materiales": 'jsonb',
  },
  'ops-notifications': {
    "cliente": 'text',
    "detalles": 'jsonb',
    "id": 'text',
    "leido": 'boolean',
    "sdv_id": 'text',
    "timestamp": 'text',
    "tipo": 'text',
  },
  'push-subscriptions': {
    "_rid": 'text',
    "createdAt": 'text',
    "subscription": 'jsonb',
    "userId": 'text',
  },
  'sdv-cancellation-audit': {
    "detalles": 'jsonb',
    "id": 'text',
    "sdv_id": 'text',
    "timestamp": 'text',
    "tipo_evento": 'text',
    "usuario_id": 'text',
    "usuario_nombre": 'text',
  },
  'sdv-reactivation-requests': {
    "cuando_procesar": 'text',
    "estado": 'text',
    "id": 'text',
    "motivo_reactivacion": 'text',
    "notas_ops": 'text',
    "nueva_fecha_entrega": 'text',
    "nueva_tarea_id": 'text',
    "procesado_at": 'text',
    "procesado_por": 'text',
    "procesado_por_nombre": 'text',
    "sdv_id": 'text',
    "solicitado_at": 'text',
    "solicitado_por": 'text',
    "solicitado_por_nombre": 'text',
  },
  'sdv-solicitudes': {
    "adjuntos": 'jsonb',
    "alertas": 'jsonb',
    "aprobadoEn": 'text',
    "articulosOdoo": 'jsonb',
    "asunto": 'text',
    "cancelado_at": 'text',
    "cancelado_por": 'text',
    "cancelado_por_nombre": 'text',
    "ciudadEntrega": 'text',
    "clienteNombre": 'text',
    "creadoAt": 'text',
    "creadoNombre": 'text',
    "creadoPor": 'text',
    "descripcion": 'text',
    "despachadaEn": 'text',
    "direccionEntrega": 'text',
    "esDecorador": 'boolean',
    "estado": 'text',
    "fechaDespacho": 'text',
    "fechaSolicitud": 'text',
    "fechaSolicitudDeseada": 'text',
    "fechaSolicitudDeseadaOriginal": 'text',
    "folio": 'text',
    "gpsCoords": 'text',
    "id": 'text',
    "modificadoPor": 'text',
    "modificadoPorNombre": 'text',
    "observaciones": 'text',
    "odooOrderRef": 'text',
    "odooOrderRefs": 'jsonb',
    "ordenOrigenOdoo": 'text',
    "receptorContacto": 'text',
    "receptorNombre": 'text',
    "rechazadaEn": 'text',
    "reprogramaciones": 'jsonb',
    "retRef": 'text',
    "retRefs": 'jsonb',
    "retState": 'text',
    "sdvAsociadaFolio": 'text',
    "sdvAsociadaId": 'text',
    "solicitudesAdicionales": 'jsonb',
    "statusHistory": 'jsonb',
    "subtipoEspecial": 'text',
    "tipoSolicitud": 'text',
    "transporteIncluido": 'boolean',
    "ubicacionDestino": 'text',
    "ubicacionOrigen": 'text',
    "ultimaModificacion": 'text',
    "wwpTareaActiva": 'boolean',
    "wwpTareas": 'jsonb',
    "wwpTaskId": 'text',
  },
  // wwp-audit: eventos heterogéneos (87 claves distintas en prod) — solo se tipan
  // las 2 columnas universales; el payload de cada evento viaja entero en _extra.
  'wwp-audit': {
    "event": 'text',
    "timestamp": 'text',
  },
  'wwp-daily-close': {
    "comment": 'text',
    "date": 'text',
    "id": 'text',
    "managerResponses": 'jsonb',
    "pending": 'jsonb',
    "role": 'text',
    "snapshot": 'jsonb',
    "submittedAt": 'text',
    "userId": 'text',
    "userName": 'text',
    "validated": 'boolean',
  },
  'wwp-inspecciones': {
    "apto": 'text',
    "combustible": 'float8',
    "conductor": 'text',
    "createdAt": 'text',
    "createdBy": 'text',
    "createdByName": 'text',
    "createdByOdooId": 'float8',
    "fecha": 'text',
    "firmaConductor": 'text',
    "fotos_condicion": 'jsonb',
    "hora": 'text',
    "id": 'text',
    "items": 'jsonb',
    "km": 'float8',
    "observacionesGenerales": 'text',
    "placa": 'text',
    "vehiculo": 'text',
  },
  'wwp-inventario-casos': {
    "creadoAt": 'text',
    "creadoBy": 'text',
    "creadoNombre": 'text',
    "descripcion": 'text',
    "estado": 'text',
    "id": 'text',
    "items": 'jsonb',
    "seedKey": 'text',
    "titulo": 'text',
  },
  'wwp-inventario-snapshots': {
    "_rid": 'text',
    "acdpNegativos": 'float8',
    "comp": 'jsonb',
    "fecha": 'text',
    "flagged": 'jsonb',
    "manos": 'jsonb',
    "reservadas": 'float8',
    "scores": 'jsonb',
    "senales": 'jsonb',
    "ts": 'float8',
  },
  'wwp-locations': {
    "_rid": 'text',
    "accuracy": 'float8',
    "at": 'text',
    "context": 'text',
    "lat": 'float8',
    "lng": 'float8',
    "taskId": 'text',
    "userId": 'text',
  },
  'wwp-lunch-breaks': {
    "allowedMinutes": 'float8',
    "compliant": 'boolean',
    "date": 'text',
    "endTime": 'text',
    "exceededMinutes": 'float8',
    "id": 'text',
    "startTime": 'text',
    "totalMinutes": 'float8',
    "userId": 'text',
    "userName": 'text',
    "userRole": 'text',
  },
  'wwp-notifications': {
    "actionRequired": 'boolean',
    "by": 'text',
    "category": 'text',
    "clickedAt": 'text',
    "coalescedAt": 'text',
    "context": 'jsonb',
    "count": 'float8',
    "createdAt": 'text',
    "deliver": 'text',
    "dueDate": 'text',
    "firstAt": 'text',
    "id": 'text',
    "message": 'text',
    "priority": 'text',
    "readAt": 'text',
    "relatedTaskId": 'text',
    "status": 'text',
    "target": 'jsonb',
    "title": 'text',
    "type": 'text',
    "urgency": 'text',
    "userId": 'text',
  },
  'wwp-role-defs': {
    "id": 'text',
    "isBuiltin": 'boolean',
    "name": 'text',
    "sectionPerms": 'jsonb',
  },
  'wwp-sessions': {
    "device": 'text',
    "expiresAt": 'text',
    "id": 'text',
    "lastActivity": 'text',
    "refreshToken": 'text',
    "userId": 'text',
  },
  'wwp-solicitudes-showroom': {
    "almacen": 'text',
    "barcode": 'text',
    "canceladoPor": 'jsonb',
    "completadoPor": 'jsonb',
    "completadoRef": 'text',
    "contId": 'text',
    "fechaCancelacion": 'text',
    "fechaCompletado": 'text',
    "fechaSolicitud": 'text',
    "id": 'text',
    "imageBase64": 'text',
    "name": 'text',
    "nota": 'text',
    "ref": 'text',
    "solicitadoPor": 'jsonb',
    "source": 'text',
    "status": 'text',
    "ubicacion": 'text',
  },
  'wwp-tasks': {
    "actionNote": 'text',
    "assignedTo": 'text',
    "assignees": 'jsonb',
    "auxDone": 'jsonb',
    "auxiliaryAssignees": 'jsonb',
    "client": 'text',
    "coManagerIds": 'jsonb',
    "completedAt": 'text',
    "createdAt": 'text',
    "createdBy": 'text',
    "deliveryAddress": 'text',
    "dependsOnPrev": 'boolean',
    "description": 'text',
    "devolucionRuta": 'jsonb',
    "dispatchCompletedAt": 'text',
    "dispatchStartedAt": 'text',
    "dueDate": 'text',
    "dueDateAuto": 'boolean',
    "escalation": 'jsonb',
    "evidence": 'jsonb',
    "executors": 'jsonb',
    "fotos_entrega": 'jsonb',
    "fotos_guia": 'jsonb',
    "fotos_recepcion": 'jsonb',
    "fotos_vehiculo": 'jsonb',
    "geoSilenceAlertAt": 'text',
    "gpsCoords": 'text',
    "id": 'text',
    "items": 'jsonb',
    "itemsUpdatedAt": 'text',
    "localidad": 'text',
    "location": 'text',
    "managerId": 'text',
    "managerName": 'text',
    "messages": 'jsonb',
    "odooRef": 'text',
    "outPendiente": 'jsonb',
    "overdue": 'boolean',
    "overdueDays": 'float8',
    "parentId": 'text',
    "phone": 'text',
    "priority": 'text',
    "receptorNombre": 'text',
    "relacionada_a_sdv": 'text',
    "requester": 'text',
    "retirado_por_cliente": 'boolean',
    "retRef": 'text',
    "retState": 'text',
    "salesperson": 'text',
    "sdvArticulos": 'jsonb',
    "sdvFolio": 'text',
    "sdvId": 'text',
    "sdvOriginalCancelada": 'text',
    "seq": 'float8',
    "staffEnd": 'text',
    "staffFrom": 'text',
    "staffStart": 'text',
    "staffTo": 'text',
    "status": 'text',
    "statusHistory": 'jsonb',
    "subIndex": 'float8',
    "taskConcept": 'text',
    "title": 'text',
    "totalHours": 'float8',
    "transporteIncluido": 'boolean',
    "type": 'text',
    "updatedAt": 'text',
    "validatedAt": 'text',
  },
  'wwp-training-courses': {
    "active": 'boolean',
    "category": 'text',
    "competency": 'text',
    "createdAt": 'text',
    "createdBy": 'text',
    "description": 'text',
    "enforceGate": 'boolean',
    "exam": 'jsonb',
    "id": 'text',
    "lessons": 'jsonb',
    "maxAttempts": 'float8',
    "passingScore": 'float8',
    "roles": 'jsonb',
    "title": 'text',
    "updatedAt": 'text',
    "validityDays": 'float8',
    "version": 'float8',
  },
  'wwp-users-auth': {
    "active": 'boolean',
    "assignedManager": 'text',
    "categoria": 'text',
    "createdAt": 'text',
    "dailySummaryEnabled": 'boolean',
    "email": 'text',
    "id": 'text',
    "lastLocation": 'jsonb',
    "lastLogin": 'text',
    "lunchTimeAllowed": 'float8',
    "name": 'text',
    "odooId": 'float8',
    "passwordHash": 'text',
    "presenceAt": 'text',
    "presenceStatus": 'text',
    "resetToken": 'text',
    "resetTokenExpiry": 'text',
    "role": 'text',
    "vehicleInspectionRequired": 'boolean',
    "workSchedule": 'jsonb',
  },
  'wwp-vehicles': {
    "fuelType": 'text',
    "id": 'text',
    "isBuiltin": 'boolean',
    "name": 'text',
    "placa": 'text',
  },
};

module.exports = TYPED_SCHEMAS;
