/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/islas/tema-opsat.ts
 * Command: astryx theme build src/islas/tema-opsat.ts --out src/islas/opsat.css
 * Generated: 2026-07-24T02:41:34.328Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const opsatTheme: DefinedTheme;
